name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "DB_HOST=mysql" > .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASS=labo03" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for services
        run: sleep 20

      - name: Run tests
        run: |
          docker exec $(docker ps -qf "name=store_manager") pytest -v